<?php
/**
 * Created by IntelliJ IDEA.
 * User: Janis
 * Date: 26.11.2015
 * Time: 14:05
 */
?>

<!-- dynamic navi -->
<table style="width:100%">
    <?php $collection = Mage::getModel('cms/page')->getCollection()->addStoreFilter(Mage::app()->getStore()->getId());?>
    <?php  $collection->getSelect()->where('is_active = 1'); ?>
    <!--     <ul id="nav"> -->
    <tr>
        <?php foreach ($collection as $page): ?>
            <?php $PageData = $page->getData(); ?>
            <?php if($PageData['identifier']!='no-route' && $PageData['identifier']!='enable-cookies' && $PageData['identifier']!='home2' && $PageData['identifier'] != 'customer-service'){ ?>
                <td class="nav-cell">
                    <a href="<?php echo $PageData['identifier']?>"><span><?php echo $PageData['title'] ?></span></a>
                </td>
            <?php } ?>
        <?php endforeach; ?>
    </tr>
    <!--   </ul> -->
</table>

<!-- Holt alle Kategorien -->
<?php
/*
$_helper = Mage::helper('catalog/category');
$_categories = $_helper->getStoreCategories();
foreach($_categories as $_category){
    $_category = Mage::getModel('catalog/category')->load($_category->getId());
    $_subcategories = $_category->getChildrenCategories();
    echo $_category->getName();
  //  echo $_category->getId();
    foreach($_subcategories as $_subcategory){
        echo $_subcategory->getName();
 //       echo $_subcategory->getId();
    }
}
*/
?>
